export const MESSAGE_TYPES = {
  EXECUTE_ACTION: 'EXECUTE_ACTION',
  ACTION_COMPLETED: 'ACTION_COMPLETED',
  ACTION_FAILED: 'ACTION_FAILED',
  RUN_CODE: 'RUN_CODE',
  CONSOLE_LOG: 'CONSOLE_LOG',
  ACTION_RESPONSE: 'ACTION_RESPONSE',
  EXECUTION_COMPLETE: 'EXECUTION_COMPLETE',
} as const;

