export const MESSAGE_TYPES = {
  EXECUTE_ACTION: 'EXECUTE_ACTION',
  ACTION_COMPLETED: 'ACTION_COMPLETED',
  ACTION_FAILED: 'ACTION_FAILED',
  RUN_CODE: 'RUN_CODE',
  CONSOLE_LOG: 'CONSOLE_LOG',
  ACTION_RESPONSE: 'ACTION_RESPONSE',
  EXECUTION_COMPLETE: 'EXECUTION_COMPLETE',
  START_DOM_SELECT: 'START_DOM_SELECT',
  STOP_DOM_SELECT: 'STOP_DOM_SELECT',
  DOM_ELEMENT_SELECTED: 'DOM_ELEMENT_SELECTED',
  DOM_SELECT_ABORTED: 'DOM_SELECT_ABORTED',
} as const;

